"""
Session Evaluation Tracker for the FS-ID Triage Agent.

Collects real-time queries and user feedback during interactive CLI runs,
accumulates ground truth dynamically, and computes the exact Data Science
benchmark metrics defined in `eval.metrics` (Action Confusion Matrix, Macro/Weighted F1,
Safety Metrics, Template Accuracy, Jaccard IoU, Brier Score, ECE, and Clarification Metrics)
in configurable batches (e.g. every 3 cases).
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
import json
import os
from typing import Any, Dict, List, Optional, Tuple

from eval.metrics import (
    compute_confusion_matrix,
    compute_safety_metrics,
    compute_jaccard_iou,
    compute_calibration,
    compute_template_accuracy,
    compute_clarification_metrics,
)
from src.models import ServiceRouterDecision


@dataclass
class SessionCase:
    """Represents a single triage case evaluated dynamically during a session."""
    case_number: int
    raw_text: str
    predicted_template: Optional[str]
    predicted_action: str
    predicted_urgency: str
    predicted_missing_fields: List[str]
    confidence: float
    loop_count: int
    generated_questions: List[str]
    rationale: str
    is_correct: Optional[bool] = None
    expected_template: Optional[str] = None
    expected_action: Optional[str] = None
    expected_urgency: Optional[str] = None
    expected_missing_fields: Optional[List[str]] = None
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class SessionTracker:
    """Tracks dynamic runtime inputs and evaluates Data Science metrics in batches."""

    def __init__(self, batch_size: int = 3) -> None:
        """Initialize tracker with configurable batch size.

        Args:
            batch_size: Number of evaluated cases before triggering a batch evaluation.
        """
        self.cases: List[SessionCase] = []
        self._eval_active: bool = False
        self._case_counter: int = 0
        self.batch_size: int = batch_size
        self.batch_count: int = 0

    def toggle_eval(self) -> bool:
        """Toggle evaluation mode on/off."""
        self._eval_active = not self._eval_active
        return self._eval_active

    def is_eval_active(self) -> bool:
        """Check if evaluation mode is active."""
        return self._eval_active

    def record_case(self, raw_text: str, decision: Optional[ServiceRouterDecision]) -> SessionCase:
        """Record a newly routed case from a ServiceRouterDecision.

        Args:
            raw_text: The user's input request.
            decision: The decision generated by the triage agent.

        Returns:
            The recorded SessionCase.
        """
        self._case_counter += 1

        predicted_template = None
        predicted_action = "ERROR"
        predicted_urgency = "UNKNOWN"
        predicted_missing: List[str] = []
        confidence = 0.0
        loop_count = 0
        generated_questions: List[str] = []
        rationale = "No decision returned."

        if decision is not None:
            if decision.match_result:
                predicted_template = getattr(decision.match_result, "top_template_id", None)

            if decision.routing_result and getattr(decision.routing_result, "routing_action", None):
                predicted_action = decision.routing_result.routing_action
            elif getattr(decision, "initial_routing_action", None):
                predicted_action = decision.initial_routing_action
            else:
                predicted_action = "UNKNOWN"

            if decision.extracted_entities:
                predicted_urgency = getattr(decision.extracted_entities, "assessed_real_urgency", "UNKNOWN")

            if getattr(decision, "initial_missing_fields", None) is not None:
                predicted_missing = list(decision.initial_missing_fields)
            elif decision.gap_result:
                predicted_missing = list(decision.gap_result.missing_required_fields)

            if decision.routing_result and hasattr(decision.routing_result, "confidence_score"):
                score = decision.routing_result.confidence_score
                confidence = float(score) if score is not None else 0.0

            if decision.clarification_state:
                loop_count = decision.clarification_state.loop_count
                if decision.clarification_state.clarification_questions:
                    generated_questions = [
                        q.target_field for q in decision.clarification_state.clarification_questions
                    ]
                elif decision.clarification_state.clarification_history:
                    generated_questions = [
                        item.get("question", "") for item in decision.clarification_state.clarification_history
                    ]

            if decision.finalizer_synthesis:
                rationale = decision.finalizer_synthesis.decision_rationale

        case = SessionCase(
            case_number=self._case_counter,
            raw_text=raw_text,
            predicted_template=predicted_template,
            predicted_action=predicted_action,
            predicted_urgency=predicted_urgency,
            predicted_missing_fields=predicted_missing,
            confidence=confidence,
            loop_count=loop_count,
            generated_questions=generated_questions,
            rationale=rationale,
        )
        self.cases.append(case)
        return case

    def record_feedback(
        self,
        case_number: int,
        is_correct: bool,
        expected_template: Optional[str] = None,
        expected_action: Optional[str] = None,
        expected_urgency: Optional[str] = None,
        expected_missing_fields: Optional[List[str]] = None,
    ) -> bool:
        """Record user feedback and return True if a batch evaluation was triggered.

        Args:
            case_number: Case number to record feedback for.
            is_correct: Whether the system's routing decision was correct.
            expected_template: Correct template ID if incorrect.
            expected_action: Correct action if incorrect.
            expected_urgency: Correct urgency tier if incorrect.
            expected_missing_fields: Correct missing fields if incorrect.

        Returns:
            bool: True if the feedback crossed a batch_size threshold.
        """
        for case in self.cases:
            if case.case_number == case_number:
                case.is_correct = is_correct
                if is_correct:
                    case.expected_template = case.predicted_template
                    case.expected_action = case.predicted_action
                    case.expected_urgency = case.predicted_urgency
                    case.expected_missing_fields = list(case.predicted_missing_fields)
                else:
                    case.expected_template = expected_template or case.predicted_template
                    case.expected_action = expected_action or case.predicted_action
                    case.expected_urgency = expected_urgency or case.predicted_urgency
                    case.expected_missing_fields = (
                        list(expected_missing_fields)
                        if expected_missing_fields is not None
                        else list(case.predicted_missing_fields)
                    )
                break

        evaluated_cases = self.get_evaluated_cases()
        if len(evaluated_cases) > 0 and len(evaluated_cases) % self.batch_size == 0:
            self.batch_count += 1
            return True
        return False

    def get_evaluated_cases(self) -> List[SessionCase]:
        """Return list of cases where user provided ground truth feedback."""
        return [c for c in self.cases if c.is_correct is not None]

    def compute_data_science_metrics(
        self, cases: Optional[List[SessionCase]] = None
    ) -> Dict[str, Any]:
        """Compute the full Data Science evaluation metrics over evaluated cases.

        Reuses the exact metric definitions from `eval.metrics`:
        - Confusion matrix & F1 scores
        - Safety metrics (P1 Recall, FNR, Cost penalty)
        - Template accuracy
        - Jaccard IoU for missing fields
        - Confidence calibration (Brier score & ECE)
        - Clarification quality (Specificity, redundancy)

        Args:
            cases: Optional list of cases to evaluate; defaults to all session cases.

        Returns:
            Dict containing the metrics payload.
        """
        target_cases = [
            c for c in (cases if cases is not None else self.cases) if c.is_correct is not None
        ]
        if not target_cases:
            return {}

        y_true_action = [c.expected_action or c.predicted_action for c in target_cases]
        y_pred_action = [c.predicted_action for c in target_cases]

        y_true_urgency = [c.expected_urgency or c.predicted_urgency for c in target_cases]
        y_pred_urgency = [c.predicted_urgency for c in target_cases]

        y_true_temp = [c.expected_template or c.predicted_template for c in target_cases]
        y_pred_temp = [c.predicted_template for c in target_cases]

        y_true_missing = [
            c.expected_missing_fields
            if c.expected_missing_fields is not None
            else c.predicted_missing_fields
            for c in target_cases
        ]
        y_pred_missing = [c.predicted_missing_fields for c in target_cases]

        y_true_binary = [1 if c.is_correct is True else 0 for c in target_cases]
        y_prob = [c.confidence for c in target_cases]

        loop_counts = [c.loop_count for c in target_cases]
        generated_questions_list = [c.generated_questions for c in target_cases]

        conf_matrix = compute_confusion_matrix(y_true_action, y_pred_action)
        safety_metrics = compute_safety_metrics(y_true_urgency, y_pred_urgency)
        temp_acc = compute_template_accuracy(y_true_temp, y_pred_temp)
        jaccards = [
            compute_jaccard_iou(t, p) for t, p in zip(y_true_missing, y_pred_missing)
        ]
        mean_jaccard = sum(jaccards) / len(jaccards) if jaccards else 0.0
        calib = compute_calibration(y_true_binary, y_prob)
        clarif = compute_clarification_metrics(
            loop_counts, y_true_missing, generated_questions_list
        )

        return {
            "total_cases": len(self.cases),
            "evaluated_cases": len(target_cases),
            "correct_cases": sum(y_true_binary),
            "accuracy": sum(y_true_binary) / len(target_cases),
            "confusion_matrix": conf_matrix,
            "safety_metrics": safety_metrics,
            "template_accuracy": temp_acc,
            "mean_jaccard_iou": mean_jaccard,
            "calibration": calib,
            "clarification": clarif,
        }

    def get_cases(self) -> List[SessionCase]:
        """Return all recorded session cases."""
        return self.cases

    def export_report(self, filepath: Optional[str] = None, batch_label: Optional[str] = None) -> str:
        """Export the comprehensive evaluation report to JSON.

        Args:
            filepath: Optional destination path.
            batch_label: Optional tag for batch naming.

        Returns:
            The filepath where the report was saved.
        """
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        if filepath is None:
            prefix = f"session_batch_{batch_label}_" if batch_label else "session_report_"
            filepath = os.path.join("data", f"{prefix}{timestamp}.json")

        os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)

        report = {
            "batch_number": self.batch_count,
            "timestamp": timestamp,
            "metrics": self.compute_data_science_metrics(),
            "cases": [
                {
                    "case_number": c.case_number,
                    "raw_text": c.raw_text,
                    "predicted": {
                        "template": c.predicted_template,
                        "action": c.predicted_action,
                        "urgency": c.predicted_urgency,
                        "missing_fields": c.predicted_missing_fields,
                        "confidence": c.confidence,
                    },
                    "ground_truth": {
                        "is_correct": c.is_correct,
                        "expected_template": c.expected_template,
                        "expected_action": c.expected_action,
                        "expected_urgency": c.expected_urgency,
                        "expected_missing_fields": c.expected_missing_fields,
                    },
                    "rationale": c.rationale,
                    "timestamp": c.timestamp,
                }
                for c in self.cases
            ],
        }

        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2)

        return filepath
